# Generated by Django 4.0.1 on 2022-01-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
