# Generated by Django 3.2.11 on 2022-10-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patient_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pharmacist',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PATIENT', 'patient'), ('DOCTOR', 'doctor'), ('PHARMACIST', 'pharmacist'), ('ADMIN', 'admin')], default='patient', max_length=10),
        ),
    ]
