# Generated by Django 4.0.1 on 2022-01-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('form', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=20)),
                ('pack', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=10)),
                ('company', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
