# Generated by Django 4.0.1 on 2022-01-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_alter_prescription_doctor_alter_prescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='realization_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='realized',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
