# Generated by Django 3.2.11 on 2022-01-29 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_requests', '0001_initial'),
        ('prescriptions', '0005_prescription_realization_date_prescription_realized'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionsegment',
            name='prescription_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='prescription_requests.prescriptionrequest'),
        ),
    ]
