# Generated by Django 3.2.11 on 2022-01-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_prescriptionsegment_prescription_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionsegment',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='prescriptions.prescription'),
        ),
    ]
