# Generated by Django 3.2.11 on 2022-01-29 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('DENIED', 'denied')], default='PENDING', max_length=10)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_prescription_request', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_prescription_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
